### ISSUE TITLE
请问有畸变的相机要怎么拼接呢

### ISSUE THREAD

**Issue by dayekuaipao** [mhhai/ImageStitch#1]
畸变的相机是不是需要标定之后再进行拼接？还是直接用原图像拼接就可以了？

**Comment by mhhai** [comment]
畸变的成像需要先进行校正，然后再标定，最后再拼接。

**Comment by mhhai** [comment]
> 畸变的相机是不是需要标定之后再进行拼接？还是直接用原图像拼接就可以了？

**Comment by mhhai** [comment]
> 畸变的相机是不是需要标定之后再进行拼接？还是直接用原图像拼接就可以了？

畸变的成像需要先进行校正，然后再标定，最后再拼接。
